# Generated by Django 6.1 on 2026-08-21 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_branch_address_remove_branch_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Obuna faolmi?'),
        ),
        migrations.AddField(
            model_name='company',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=10, verbose_name="Oylik to'lov summasi"),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Obuna tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Do'kon / Kompaniya nomi"),
        ),
    ]
