# Generated by Django 6.1 on 2026-09-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_is_active_company_monthly_fee_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='UZS', max_length=10, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.CharField(default='uz', max_length=10, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Asia/Tashkent', max_length=50, verbose_name='Vaqt belgisi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CASHIER', 'Kassir'), ('VIEWER', "Ko'ruvchi")], default='CASHIER', max_length=10),
        ),
    ]
