# Generated by Django 6.1 on 2026-09-05 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_currency_company_language_company_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Yaratish'), ('UPDATE', 'Tahrirlash'), ('DELETE', "O'chirish"), ('LOGIN', 'Kirish'), ('LOGOUT', 'Chiqish')], max_length=20, verbose_name='Amal')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='Obyekt ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Obyekt nomi')),
                ('changes', models.JSONField(default=dict, verbose_name="O'zgarishlar")),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Firma')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-created_at'],
            },
        ),
    ]
