# Generated by Django 6.1 on 2026-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_is_active_company_monthly_fee_company_phone_and_more'),
        ('inventory', '0005_category_company_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=50, verbose_name='Shtrix-kod'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'barcode')},
        ),
    ]
