# Generated by Django 6.1 on 2026-08-08 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik karta'), ('SPLIT', 'Aralash (Naqd + Karta)')], default='CASH', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy summa')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami tan narxi')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sof foyda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.branch')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Middori')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotilgandagi tan narxi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotilgan narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami sotish summasi')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
