# Generated by Django 6.1 on 2026-08-09 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0003_alter_category_options_remove_category_company_and_more'),
        ('sales', '0004_debtpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar bazasi'},
        ),
        migrations.AlterModelOptions(
            name='debtpayment',
            options={'verbose_name': "Qarz to'lovi", 'verbose_name_plural': "Qarz to'lovlari"},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Savdo (Chek)', 'verbose_name_plural': 'Savdolar (Xaridlar)'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Savdo tarkibidagi tovar', 'verbose_name_plural': 'Savdo tarkibidagi tovarlar'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Qarzdorlik balansi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mijoz F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan kassir'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="To'lov vaqti"),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd pul'), ('CARD', 'Plastik karta')], default='CASH', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Savdo vaqti'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='Nasiya savdomi?'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sof foyda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Jami tannarx'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tannarxi'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotilish narxi'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Tovar'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12, verbose_name='Sotilgan soni'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Savdo (Chek)'),
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Qaytarilgan soni')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Qaytarilgan pul')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Qaytarish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qaytarilgan vaqt')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Filial')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Kompaniya')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Tovar')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale', verbose_name='Savdo (Chek)')),
            ],
            options={
                'verbose_name': 'Tovar qaytarilishi (Возврат)',
                'verbose_name_plural': 'Tovarlarni qaytarish (Возвратlar)',
            },
        ),
    ]
