# Generated by Django 6.1 on 2026-08-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_branch_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salereturn',
            options={'verbose_name': 'Tovar qaytarilishi', 'verbose_name_plural': 'Tovarlarni qaytarish'},
        ),
    ]
